repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: mixed-line-ending
    -   id: sort-simple-yaml

- repo: https://github.com/ansible/ansible-lint
  rev: v5.2.1
  hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
