name: Ansible

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distros:
          - ghcr.io/artis3n/docker-ubuntu2104-ansible:latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Use Cache
        uses: actions/cache@v3.0.4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashfiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install packages
        run: |
          pipenv install --dev
          pipenv run ansible-galaxy role install -r requirements.yml
          pipenv run ansible-galaxy collection install -r requirements.yml

      - name: Molecule
        run: pipenv run molecule test
        env:
          MOLECULE_DISTRO: "${{ matrix.distros }}"
          # https://www.jeffgeerling.com/blog/2020/getting-colorized-output-molecule-and-ansible-on-github-actions-ci
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
